"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Loader2 } from "lucide-react";
import { getRecommendations } from "@/actions/recommendationActions";
import { getProductsByNames } from "@/lib/products";
import type { Product } from "@/lib/types";
import ProductCarousel from "./ProductCarousel";
import { useToast } from "@/hooks/use-toast";

export default function RecommendedProducts() {
  const [recommendations, setRecommendations] = useState<Product[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleGetRecommendations = async () => {
    setIsLoading(true);
    setRecommendations([]);
    const result = await getRecommendations();
    if (result.success && result.data) {
      const products = await getProductsByNames(result.data);
      setRecommendations(products);
    } else {
      toast({
        variant: "destructive",
        title: "Recommendation Error",
        description: result.error || "Could not fetch recommendations.",
      });
    }
    setIsLoading(false);
  };

  return (
    <div className="w-full bg-secondary">
      {recommendations.length > 0 ? (
        <ProductCarousel title="Recommended For You" products={recommendations} />
      ) : (
        <div className="container mx-auto py-16 text-center">
            <h2 className="text-3xl font-bold font-headline mb-4">Want to see something special?</h2>
            <p className="text-muted-foreground mb-8 max-w-2xl mx-auto">Click the button below to get product recommendations generated by AI, tailored just for you based on your browsing habits.</p>
          <Button
            size="lg"
            onClick={handleGetRecommendations}
            disabled={isLoading}
            className="bg-accent hover:bg-accent/90 text-accent-foreground"
          >
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              "Get My Recommendations"
            )}
          </Button>
        </div>
      )}
    </div>
  );
}
